name: Gradle publish

on:
  workflow_dispatch:
  release:
    types: [ created ]

jobs:
  publish:
    environment:
      name: publish
    strategy:
      matrix:
        os: [ macOS-latest, windows-latest ]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: 21.2.0
          java: java16
          arch: amd64
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - if: matrix.os == 'windows-latest'
        shell: cmd
        run: >
          ./gradlew release --no-daemon --build-cache -Ppublishing.enabled=true
          -Ppublishing.space.user=${{ secrets.SPACE_APP_ID }}
          -Ppublishing.space.token=${{ secrets.SPACE_APP_SECRET }}
      - if: matrix.os == 'macOS-latest'
        run: >
          ./gradlew release --no-daemon --build-cache -Ppublishing.enabled=true -Ppublishing.platform=macosX64
          -Ppublishing.space.user=${{ secrets.SPACE_APP_ID }}
          -Ppublishing.space.token=${{ secrets.SPACE_APP_SECRET }}
